name: htmlhint

on:
  pull_request:
    paths:
      - '**/*.html'
  push:
    branches:
      - main
    paths:
      - '**/*.html'

jobs:
  lint:
    name: HTML Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run htmlhint
        run: |
          npm --version
          npx --yes htmlhint "**/*.html"
