name: Lighthouse CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci || true
          npm install -g @lhci/cli

      - name: Serve site
        run: |
          npm install -g serve
          serve -s . -l 8080 &
          sleep 2

      - name: Run Lighthouse CI (write filesystem report)
        run: |
          # First run: write LHCI output to ./.lighthouseci so we can upload it as an artifact
          lhci autorun --collect.url=http://localhost:8080 --collect.settings.chromeFlags="--no-sandbox --headless" --upload.target=filesystem || true

      - name: Run Lighthouse CI (temporary-public-storage)
        run: |
          # Second run: upload to temporary-public-storage to get a public report URL
          lhci autorun --collect.url=http://localhost:8080 --collect.settings.chromeFlags="--no-sandbox --headless" --upload.target=temporary-public-storage || true

      - name: Run standalone Lighthouse and save HTML report
        run: |
          # Generate a standalone Lighthouse HTML report (fallback) so we can always upload an artifact
          npx -y lighthouse http://localhost:8080 --output html --output-path=./lighthouse-report.html --quiet --chrome-flags='--no-sandbox --headless' || true

      - name: Upload artifact (report)
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: |
            ./.lighthouseci/**
            ./lighthouse-report.html
