name: lighthouse-ci

on:
  push:
    branches: [ main, 'blackboxai/fix-github-actions-versions' ]
  pull_request:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install http-server
        run: npm install -g http-server

      - name: Serve site and run Lighthouse
        run: |
          # start a static server in background
          http-server -p 8080 -c-1 . &
          sleep 1
          npx --yes lighthouse http://127.0.0.1:8080 --output html --output-path tmp-lh-artifact/lighthouse-report.html --chrome-flags="--headless --no-sandbox"

      - name: Upload Lighthouse report
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: tmp-lh-artifact/lighthouse-report.html
