name: Smoke tests (assets)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  smoke-test:
    name: Run asset smoke-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci

      - name: Start static server
        run: |
          # start a small static server in background
          python -m http.server 8000 &
          # give the server a moment to start
          sleep 2

      - name: Run smoke-test
        run: |
          npm run test:smoke
        env:
          CI: true
